add telegram publisher example
volunteer-prb/podcasts-api pull request #2
Opened 2022-05-18 17:12 UTC by dkotlyar

2022-05-20 22:39 UTC, dkotlyar commented
# Publisher service

Consumes notification topic from other service, prepare and publish 
messages to selected social media sources.

## Build

```commandline
docker build -t volunteer-prb/podcasts-api-publisher .
```

## Running

Local
```commandline
export TELEGRAM_TOKEN=<put_bot_token_here>
cd src && python main.py
```

In docker 
```commandline
docker run -e TELEGRAM_TOKEN=<put_bot_token_here> \
  -e REDIS_HOST=<redis_host> \
  --name publisher --rm \
  volunteer-prb/podcasts-api-publisher
```

## Example 

```python
import json

from redis import Redis


envelope = dict(
    title='Podcasts API Example',
   description='Project for uploading videos from YouTube as audio podcasts to TG and Soundcloud',
   hashtags=['volunteer', 'prb', 'media'],
   publisher='Volunteer PRB',
   photo='https://file-examples.com/storage/feb04797b46286b5ea5f061/2017/10/file_example_JPG_500kB.jpg',
   audio='https://file-examples.com/storage/feb04797b46286b5ea5f061/2017/11/file_example_MP3_700KB.mp3',
   recipients=[
       dict(
           _type_ = 'telegram',
           channel_id=-1000000000000  # replace it by you channel id
       )
   ]
)

r = Redis()
r.publish('notification_topic', json.dumps(envelope))
```

2022-05-21 15:01 UTC, dkotlyar commented
import json
import uuid

from redis import Redis


envelope = dict(
    title='Podcasts API Example',
    description='Project for uploading videos from YouTube as audio podcasts to TG and Soundcloud',
    hashtags=['volunteer', 'prb', 'media'],
    publisher='Volunteer PRB',
    photo='https://transfer.sh/get/shqEBi/photo.jpg',
    audio='https://transfer.sh/get/vYyWP8/audio.mp3',
    recipients=[
        dict(
            _type_ = 'telegram',
            channel_id=-1000000000000  # replace it by you channel id
        )
    ]
)

r = Redis()
id = str(uuid.uuid4())
data = json.dumps(envelope)
print(id, data)
r.set(f'notification_topic_{id}', data)
r.rpush('notification_topic_list', id)

id = str(uuid.uuid4())
envelope['title'] = 'Podcasts Second API Example'
data = json.dumps(envelope)
print(id, data)
r.set(f'notification_topic_{id}', data)
r.rpush('notification_topic_list', id)

2022-05-22 16:30 UTC, dkotlyar commented
# Publisher service

Consumes notification topic from other service, prepare and publish messages to selected social media sources.

## Build

```commandline
docker build -t volunteer-prb/podcasts-api-publisher .
```

## Running

Local
```commandline
export TELEGRAM_TOKEN=<put_bot_token_here>
cd src && celery --app=publisher --broker=redis://localhost worker --loglevel=INFO
```

In docker 
```commandline
docker run -e TELEGRAM_TOKEN=<put_bot_token_here> \
  -e BROKER_URL=redis://<redis_host> \
  --name publisher --rm \
  volunteer-prb/podcasts-api-publisher
```

In docker compose (increase maximum audio size to 2GB)
```yaml
version: '3.8'
services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: <put_telegram_api_id>
      TELEGRAM_API_HASH: <put_telegram_api_hash>
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api

  publisher:
    image: volunteer-prb/podcasts-api-publisher:latest
    environment:
      TELEGRAM_SERVER: http://telegram-bot-api:8081
      TELEGRAM_TOKEN: <put_bot_token_here>
      BROKER_URL: redis://<redis_host>
    depends_on:
      - telegram-bot-api
```

Run with scale factor 3

```commandline
docker-compose up --scale publisher=3
```

## Example

```python
from publisher import publish


envelope = dict(
    title='Podcasts API Example',
    description='Project for uploading videos from YouTube as audio podcasts to TG and Soundcloud',
    hashtags=['volunteer', 'prb', 'media'],
    publisher='Volunteer PRB',
    photo='https://transfer.sh/get/shqEBi/photo.jpg',
    audio='https://transfer.sh/get/vYyWP8/audio.mp3',
    recipients=[
        dict(
            _type_='telegram',
            channel_id=-1000000000000  # replace it by you channel id
        )
    ]
)

publish.delay(envelope)
```

2022-05-23 10:12 UTC, andreinechaev requested changes

2022-05-23 10:12 UTC, andreinechaev commented on publisher/src/telegram/publisher.py
> +def publish(envelope: Envelope):
Please consider more granular methods for future reusability.

2022-05-23 10:12 UTC, andreinechaev commented on publisher/src/telegram/publisher.py
> +    for recipient in [rec for rec in envelope.recipients if isinstance(rec, TelegramRecipient)]:
such blocking for-loops are good candidates for queuing mechanism. Consider using Celery

2022-05-23 13:35 UTC, dkotlyar commented on publisher/src/telegram/publisher.py
> +    for recipient in [rec for rec in envelope.recipients if isinstance(rec, TelegramRecipient)]:
good remark, i'll do that

2022-05-23 20:24 UTC, dkotlyar commented
## Changes 

* Replaced blocking for-loops with queuing mechanism
* Added dataclass serializer
* Message splitting function moved out for future reusability
* Updated README, updated Example of usage

## Example
```python
from app.objects.Envelope import EnvelopeBody, Envelope
from app.objects.Recipient import TelegramRecipient
from app.publisher import publish


envelope = Envelope(
    body=EnvelopeBody(
        title='Podcasts API Example',
        description='Project for uploading videos from YouTube as audio podcasts to TG and Soundcloud',
        hashtags=['volunteer', 'prb', 'media'],
        publisher='Volunteer PRB',
        photo='https://transfer.sh/get/shqEBi/photo.jpg',
        audio='https://transfer.sh/get/vYyWP8/audio.mp3',
    ),
    recipients=[
        TelegramRecipient(
            channel_id=-1000000000000  # replace it by you channel id
        )
    ]
)

publish.delay(envelope)

```

2022-05-24 08:25 UTC, eIGato commented on mediamanager/main.py
> +    ignore_result=False
Add a trailing comma.

2022-05-24 08:28 UTC, eIGato commented on publisher/app/telegram/telegram_bot_api.py
> +    The Bot API is an HTTP-based interface created for developers keen on building bots for Telegram.
Split the line to fit in 79 (or 80) chars.

2022-05-24 08:31 UTC, eIGato commented on publisher/app/telegram/telegram_bot_api.py
> +        response = requests.post(f'{self.__server}/bot{self.__token}/{method_name}?{args}',
No lemmings please. Use uniform indents and feed the lines right after opening parentheses.

2022-05-24 10:00 UTC, dkotlyar commented on publisher/app/telegram/telegram_bot_api.py
> +        if response.status_code == 200 and (json := response.json()) and \
How can I change long if condition without backslashes in the line end?

2022-05-28 18:30 UTC, dimon222 commented on publisher/app/telegram/telegram_bot_api.py
> +                and 'ok' in json and json['ok'] is True and 'result' in json:
Perhaps we should just check the status code only?
```python
response.raise_for_status()
return json.get('result')
```

2022-05-28 18:36 UTC, dimon222 commented on publisher/app/telegram/telegram_bot_api.py
> +        )
You don't need to do this work with manually reconstructing GET params, there's "good practice" sauce out of the box. Keep `args` as dict and then pass it as `data` argument in function.
```python
response = requests.post(
            url=f'{self.__server}/bot{self.__token}/{method_name},
            json=dict_filter(json),
            data=args,
            files=files,
        )

2022-05-28 18:38 UTC, dimon222 commented
Maybe its a minor thing, but since there's relatively big adjustment done in this PR and my "annoying" side recommendation would be to avoid using conflicting "standard lib" naming for any of arguments.
That means using variable like `json` should be discouraged as there's library `json` that might cause serious confusion. Instead we could consider using `json_body`, `body` or such.

2022-05-28 18:43 UTC, dimon222 commented on publisher/app/telegram/publisher.py
> +    if photo is not None:
Perhaps can be simplified to more pythonic:
```python
if photo:
```

2022-05-28 18:45 UTC, dimon222 commented on publisher/app/telegram/telegram_bot_api.py
> +                if len(buffer.strip()) > 0:
More pythonic:
```python
if buffer.strip():
```

2022-05-29 08:16 UTC, dkotlyar commented on publisher/app/telegram/telegram_bot_api.py
> +                and 'ok' in json and json['ok'] is True and 'result' in json:
I'm not sure we should just check only status code, I rewrote this section with raise error contains Telegram description.

```python
try:
    if not response.json().get('ok'):
        raise TelegramBotError(response.json().get('description'))
    return response.json().get('result')
except json.decoder.JSONDecodeError:
    response.raise_for_status()
    raise TelegramBotError('Not JSON response')
```

2022-05-29 11:22 UTC, andreinechaev reviewed
Please rebase on master.
Please consider simple testing.
Besides those remarks - it's an exemplary PR with documentation and clear execution. Good work!

2022-05-29 13:10 UTC, dkotlyar commented
> Please rebase on master. Please consider simple testing. Besides those remarks - it's an exemplary PR with documentation and clear execution. Good work!

Something went wrong while rebase, I hope it's okay, I could made only force-push.

About simple testing I wrote an example [above](https://github.com/volunteer-prb/podcasts-api/pull/2#issuecomment-1135104721) to run and publish to Telegram. What do you recommend to add to my PR? Maybe I can add test function to check Telegram answer, but I'm not sure. 

Thank you for your remarks.

2022-05-30 19:48 UTC, andreinechaev commented on publisher/app/telegram/telegram_bot_api.py
> +class TelegramBot:
Looks like we're reinventing the wheel
Why not using the python lib https://github.com/python-telegram-bot/python-telegram-bot ?

2022-05-30 20:23 UTC, andreinechaev commented on publisher/app/telegram/telegram_bot_api.py
> +class TelegramBot:
nvm. The solution uses local sever to upload larger files.

2022-05-30 20:23 UTC, andreinechaev approved these changes

2022-05-30 20:24 UTC, merged