Various corrections + Dockerfile
volunteer-prb/podcasts-api pull request #3
Opened 2022-05-19 23:31 UTC by dimon222

1. Fix npm registry references to public NPM
2. Add Dockerfile for easier containerization/local testing for both front-end and back-end
3. Minor restructuring of requirements.txt and conda-forge (it might be wrong, but up for discussion)

How to "docker build" for front-end:
```sh
docker build webapp/frontend -t frontend
```
then run with ` docker run -it -p 127.0.0.1:1234:80 frontend`

How to "docker build" for back-end:
```sh
docker build . -f ./webapp/backend/Dockerbuild -t backend
```
then run with `docker run -it -p 127.0.0.1:1234:5000 backend`

2022-05-24 08:21 UTC, eIGato commented on webapp/backend/Dockerfile
> +CMD [ "flask", "run" ]
Please add a line feed.

2022-05-24 08:23 UTC, eIGato commented on webapp/frontend/Dockerfile
> +
Please remove a line feed.

2022-05-24 08:23 UTC, eIGato commented on webapp/backend/app.py
> +    from main import main as main_blueprint
`from .main`

2022-05-24 12:50 UTC, dimon222 commented on webapp/backend/app.py
> +    from main import main as main_blueprint
```
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 77, in find_best_app
    app = app_factory()
  File "/app/app.py", line 19, in create_app
    from .main import main as main_blueprint
ImportError: attempted relative import with no known parent package
```

2022-05-30 20:35 UTC, andreinechaev requested changes
`pytest` should work for future CI. 
Current behavior ```E   ModuleNotFoundError: No module named 'webapp'```

2022-05-30 20:36 UTC, dimon222 commented
> `pytest` should work for future CI. Current behavior `E ModuleNotFoundError: No module named 'webapp'`

How to replicate? As far as I'm aware nothing is present in repo currently for pytest to work.

2022-05-30 20:49 UTC, dimon222 commented
Do we plan to run pytest globally or is it per each app in repo? Currently its a bit chaotic with parts split on folders, but due to our shared `mediamanager` library it makes things more complicated.

2022-05-30 21:04 UTC, dimon222 commented
Above comment can be taken as separate conversation for future. Fixed tests for this PR particularly.

2022-06-01 21:59 UTC, dimon222 commented
PR is obsolete (necessary features are already merged). UI Dockerfile will be contributed separately.
Closed.

2022-06-01 21:59 UTC, closed without merging